Django_Level_Four/Basic_Templates/urls.py
from django.urls import path
from Basic_Templates import views

#TEMPLATE TAGGING
app_name ='Basic_Templates'

urlpatterns=[
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
 ]

Django_Level_Four/Django_Level_Four/urls.py
from django.contrib import admin
from django.urls import path,include
from Basic_Templates import views

urlpatterns = [
    path('',views.index,name='index'),
    path('Basic_Templates/',include('Basic_Templates.urls')),
    path('admin/', admin.site.urls),
]

Django_Level_Four/Basic_Templates/models.py
from django.db import models

# Create your models here.

Django_Level_Four/Basic_Templates/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'Basic_Templates/index.html',context_dict) 

def other(request):
    return render(request,'Basic_Templates/other.html')

def relative(request):
    return render(request,'Basic_Templates/relative_url_templates.html')

Django_Level_Four/templates/Basic_templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Page Title</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
    crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li> <a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li> <a class="navbar-link" href="{% url 'Basic_Templates:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
           {% block body_block %}
           <!-- Anything outside of this will be inherited if you extend! -->
           {% endblock %}
    </div>
</body>
</html>

Django_Level_Four/templates/Basic_templates/index.html
<!DOCTYPE html>
{% extends "Basic_Templates/base.html" %}
    {% block body_block %}
        <h1>WELCOME OT INDEX!</h1>
        <!--<h1>This is index.html page showing!</h2>-->
        <!--<h2>{{ text|upper }}</h2>-->
        <h2>{{ text|cut:'world' }}</h2>
        <h2>{{ number|add:"99" }}</h2>
    {% endblock %}

Django_Level_Four/templates/Basic_templates/other.html
<!DOCTYPE html>
{% extends "Basic_Templates/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER!</h1>
    <h2>This is an example of template inheritance!</h2>
  {% endblock %}

Django_Level_Four/templates/Basic_templates/relative_url_templates.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES!</h1>
    <a href="{% url 'Basic_Templates:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN PAGE</a>
    <a href="{% url 'index' %}">LINK TO INDEX!</a>
</body>
</html>